spring:
  application:
    name: cosmosdb-nosql-quickstart
  cloud:
    azure:
      cosmos:
        endpoint: https://localhost:8081/
        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        database: college
        populate-query-metrics: true

server:
  port: 8082

