spring:
  application:
    name: keyvault
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: https://az204learnkeyvalt.vault.azure.net/
server:
  port: 8085



